_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 103
                - 106
            "2":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 103
                - 106
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.0
            "5": 0.18.5
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-arm64
