wandb_version: 1

ACCELERATOR:
  value: gpu
BATCH_SIZE:
  value: 32
DATA_DIR:
  value: ../data/
DEVICES:
  value:
  - 0
FILE_NAME:
  value: data_clean.npy
INPUTSIZE:
  value: 92
LEARNING_RATE:
  value: 0.0001
NUM_EPOCHS:
  value: 100
NUM_WORKERS:
  value: 0
OUTPUTSIZE:
  value: 1
PRECISION:
  value: 16-mixed
optimizer:
  value: adam
