wandb_version: 1

ACCELERATOR:
  value: gpu
BATCH_SIZE:
  value: 32
DATA_DIR:
  value: ../data/
DEVICES:
  value:
  - 0
FILE_NAME:
  value: data_clean.npy
INPUTSIZE:
  value: 92
NUM_WORKERS:
  value: 0
OUTPUTSIZE:
  value: 1
PRECISION:
  value: 16-mixed
epochs:
  value: 100
learning_rate:
  value: 0.0001
optimizer:
  value: adam
